### PR TITLE
Add some subfolder_patterns

### PR DESCRIPTION
**Pull request by DriverXX**
I added some some subfolder patterns that i think are useful.
And I also properly renamed the old ones which otherwise seems to use the artist tag, but instead they use the album-artist tag

### CODE REVIEW

**Comment by zeppelinj** [comment]
are you talking to me? because I don't Know how to code

**Comment by sezanzeb** [comment]
album-artist gets populated here if not present: https://github.com/kassoulet/soundconverter/blob/d55d6a6c063b16ae679a53bcaa30ecacb83757e3/soundconverter/namegenerator.py#L136

I think the benefit of that is, that as long as there is either only an artist or only an album-artist, the path will be populated correctly.

**Comment by sezanzeb** [comment]
I think having a text-input that lets the user specify their own custom format string for subfolders would be a nice feature.

**Comment by kassoulet** [comment]
> I think having a text-input that lets the user specify their own custom format string for subfolders would be a nice feature. Possibly as an option below "Create subfolders:" and a radio button that selects only one of the two options (dropdown or user specified text)

The Filename pattern text-input can already be used to set custom folders/filenames patterns.

**Pull request closed without merging**
