### PR TITLE
rewriting task, converter and queue architecture

### PR DESCRIPTION
**Pull request by sezanzeb**
I'm using this documentation almost all the time by the way: https://lazka.github.io/pgi-docs/

Stats as of 06. August:

+2133 -244 from tests

+493 -187 from the batch mode

+2246 -2030 for the rest

# Changes

**Features**

- faster scanning of directories
- more precise calculation of the remaining time
- aligned some things in the settings dialog
- added filename and line number to `--debug` logs
- in batch mode, abr, cbr and vbr can be specified like `-f mp3 -m abr`.
- batch mode logs errors to the console if the cli args are used wrong
- batch mode supports path patterns like `-p {artist}/{album}/{title}`
- batch mode can select whether to skip, overwrite or increment files when the output already exists
- the invalid files dialog shows more of the path of each file than just the filename and has more beautiful paddings
- batch mode supports arbitrary bitrates that are not available in the ui
- info logs are colored as well with `--debug`

**Bugs**

- faac did not respect bitrate settings
- soundfile objects from the discovery step are kept for conversion, hence fixing the mp4mux tag message problem because tags are already there https://github.com/kassoulet/soundconverter/pull/36

**Quality**

- more unittests. went from 36 to 105 tests and from 79 to 502 assertions.
- went from a pylint rating of 7.49 to 8.83
- fixed confusion between self.basename and basename in get_target_name
- avoiding redundancy of storing stuff in `settings` and the gio settings at the same time
- reduced confusion between various basename, folder and pattern variables in `TargetNameGenerator`
- added many docstrings, especially to new functions
- no more confusion between functions like `done` vs `finished`, `__init__` vs `init`
- removed unnecessary forwarding of Gio settings parameters, instead querying them exactly when they are needed, (some of them still need to be stored in the converter class though to avoid them getting changed during conversion by interacting with the ui) thus reducing function header sizes and complexity
- batch mode uses Gio settings (without writing them persistently) in order to be more compatible to the rest of the code
- tasks have less inheritance. Converter only inherits from task
- taskqueue doesn't need any inheritance anymore
- no more event emitting, but rather hardcoded calls to needed functions when they are needed, because the converter class doesn't need to cover for various use cases that require different code to be executed on events. Reduces complexity
- moved code that can be generalized out of ui.py, so that it can be potentially used by the batch mode.
- removed unused imports, variables, functions and classes
- I'm pretty sure ftp uris in the tests were wrong and should start with ftp:// (see https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax)
- sound_files only accept uris as parameters, selected_folder may only be an uri as well, and patterns may not be uris, which means the target name code can focus on a better defined set of rules and work well within that.
- using discover_uri for tagreader and typefinder, which is faster and less complex. Multithreading is used to further increase the performance of the discoverers (which, however, added some complexity back)
- added some tags to c.mp3 for tests
- saving some redundancy of progress queries
- added screenshot of the batch mode to the readme
- moved logic of moving temporary files to final files to the converter class.

### CODE REVIEW

**Comment by sezanzeb** [comment]
@kassoulet why are we using URIs instead of normal paths?

**Comment by sezanzeb** [comment]
> @kassoulet why are we using URIs instead of normal paths?
> 
> It seems like almost all the path related variables can be either an URI or a normal path, which makes handling this stuff **really** hard. It's no surprise that this is a source of bugs
> 
> The tests show examples with ssh:// and such, but does that actually work? Is that ever used?
> 
> [EDIT]
> well, I guess it works: https://gstreamer.freedesktop.org/documentation/gio/giosink.html?gi-language=c

It may possible improve by forcing only specific formats. e.g. forcing the sound_file parameters to be URIs

**Comment by kassoulet** [comment]
Yep, you can read/write anywhere gio can. So it works over ftp or sftp URIs.

**Comment by sezanzeb** [comment]
> Yep, you can read/write anywhere gio can. So it works over ftp or sftp URIs.

ok thanks. I think enforcing some rules on parameters helped quite a bit to get it working. The naming code doesn't have to cover for a sheer infinite number of possibilities and edge cases anymore.

**Comment by sezanzeb** [comment]
@kassoulet Could you please try this branch and do some conversion of your own files to see if it still works?

Thanks

The profile code should still be relatively untouched, but the problem with it most likely persists.

**Comment by sezanzeb** [comment]
the gnome audio profile editing utility ("gnome-audio-profiles-properties" or "libgnome-media-profiles") is not available in the ubuntu or arch repos (only some very outdated package in the AUR exists from 5 years ago). 

Also, after doing some quick search in the sound-juicer repo, it doesn't seem to have support for gnome audio profiles anymore. There used to be an "Edit Profiles" button https://help.gnome.org/users/sound-juicer/stable/sound-juicer.html but not anymore.

@kassoulet what do do with the profile code? To me it seems that gnome audio profiles is not used anymore anywhere.

**Comment by kassoulet** [comment]
As gnome audio profiles are not really used anymore, yes you can remove the support for them.

The new code is working nice for me. Now you should change the version to 4.0, and add yourself as co-author, you deserve it.

**Comment by sezanzeb** [comment]
> As gnome audio profiles are not really used anymore, yes you can remove the support for them.
> 
> The new code is working nice for me. Now you should change the version to 4.0, and add yourself as co-author, you deserve it.

Thanks!

**Comment by sezanzeb** [comment]
ping @kassoulet

**Pull request merged**
